import { test, expect } from '@playwright/test';

test('Searching for Employee with Admin role filter should display No Records Found', async ({ page }) => {
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
  await page.getByRole('textbox', { name: 'Username' }).click()
  await page.getByRole('textbox', { name: 'Username' }).fill('Admin')
  await page.getByRole('textbox', { name: 'Username' }).press('Tab')
  await page.getByRole('textbox', { name: 'Password' }).fill('admin123')
  await page.getByRole('textbox', { name: 'Password' }).press('Enter')
  await page.getByRole('button', { name: 'Login' }).click()
  await page.getByRole('link', { name: 'Admin' }).click()
  await page.getByRole('textbox').nth(1).click()
  await page.getByRole('textbox').nth(1).fill('Ramu')
  await page.locator('form i').first().click()
  await page.getByRole('option', { name: 'Admin' }).click()
  await page.getByRole('button', { name: 'Search' }).click()
  await expect(page.getByText('No Records Found')).toBeVisible()
  await page.locator('div').filter({ hasText: /^No Records Found$/ }).nth(1).click()
})

test('Searching for Employee by their username should only display them in the records', async ({ page }) => {
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
  await page.getByRole('textbox', { name: 'Username' }).click()
  await page.getByRole('textbox', { name: 'Username' }).fill('Admin')
  await page.getByRole('textbox', { name: 'Username' }).press('Tab')
  await page.getByRole('textbox', { name: 'Password' }).fill('admin123')
  await page.getByRole('textbox', { name: 'Password' }).press('Enter')
  await page.getByRole('button', { name: 'Login' }).click()
  await page.getByRole('link', { name: 'Admin' }).click()
  await page.getByRole('textbox').nth(1).fill('FMLName')
  await page.getByRole('button', { name: 'Search' }).click()
  await expect(page.getByText('FMLName')).toBeVisible()
})
